/*jslint node:true */
'use strict';

module.exports = function shell(grunt) {
    // Load task
    grunt.loadNpmTasks('grunt-shell');

    // Options
    return {
        // grunt.file.expandMapping doesn't detect the files generated by
        // browserify and sass
        gruntCompact: {
            command: 'grunt compact'
        }
    };
};